### PR TITLE
Implements compute_track

### PR DESCRIPTION
**Pull request by TheYsconator**
A continuation of #91.

As per your suggestion, I have added the `compute_track` as an argument to `Flight.cumulative_distance()`, including its functionality.

I compared the existing 'track' column of the Belevingsvlucht with the newly added 'compute_track'. The results are in a PDF hosted on [Google Drive](https://drive.google.com/file/d/161oOxJwqofumCmj-esFwR5Nelje-g0wC/view?usp=sharing) (about 3 MB).

Please let me know if I can improve anything. (The 0.0's and 180.0's strike me odd in particular.) Sorry it took so long; this was indeed way more easy to implement than I expected.

### CODE REVIEW

**Comment by xoolive** [comment]
Indeed, we have an issue for track angles between 180 and 360. It looks like 190 becomes 170, 210 becomes 150, etc.

visualization

I would recommend to add a proper test on this example in `tests/test_flight.py`
```python
(
    belevingsvlucht.last("3H")
    .first("30T")
    .cumulative_distance(compute_track=True)
    .encode(["compute_track", "track"])
)
```

Maybe for the final test, it is better to improve the plot with an extra `filter()`:
```python
(
    belevingsvlucht.last("3H")
    .first("30T")
    .cumulative_distance(compute_track=True)
    .filter(compute_track=17)
    .encode(["compute_track", "track"])
)
```

Do you want/think you could give it a first shot?

**Comment by TheYsconator** [comment]
Yes I would definitely like to try to give that a shot! I'll start by implementing the tests, test those on my computer, and then I'll update this PR.

**Comment by TheYsconator** [comment]
Alright, I think I've both solved (hotfixed?) the issue and added some tests to the existing `test_cumulative_distance()`.

Please let me know if I should add the tests to a separate test-case instead.

I've also added a default compute_track value to filter(), though that was not requested per se, so do let me know if I should change/undo that.

**Comment by xoolive** [comment]
Thank you for your help. I also fixed a small glitch and changed (my own) nonsense test.

**Comment by TheYsconator** [comment]
Hey Xavier!

I'm sorry to come back to this resolved issue, but  I think I know of a way to resolve some of the 'peaks' in the tests without applied filter. With the median filter applied, the correlation between computed_track and (measured track is quite high (.99, vs .7 without median filter for the belevingsvlucht). However, since applying a median filter requires data points from 'the future' I'm in particular interested in seeing if I can increase that correlation without the median filter. (For my project I need to pretend that data points 'from the future' are not available.)

Shall I make a PR when I believe I got that working, so that you can decide whether or not you would like to include it in the public release?

**Comment by xoolive** [comment]
Alstublieft, any input is welcome!

**Pull request merged**
